const data = [
  {
    name: "TK Cookies N' Cream",
    price: "39php",
    bgImage: "paper/paper1.jpeg",
    section: "blue",
    subSection: "Classic Milktea",
  },
  {
    name: "TK Hokaido",
    price: "39php",
    bgImage: "paper/paper2.jpeg",
    section: "blue",
    subSection: "Classic Milktea",
  },
  {
    name: "TK Taro",
    price: "39php",
    bgImage: "paper/paper3.jpeg",
    section: "blue",
    subSection: "Classic Milktea",
  },
  {
    name: "TK Wintermenlon",
    price: "39php",
    bgImage: "paper/paper4.jpeg",
    section: "blue",
    subSection: "Classic Milktea",
  },
  {
    name: "TK Okinawa",
    price: "39php",
    bgImage: "paper/paper5.jpeg",
    section: "blue",
    subSection: "Classic Milktea",
  },
  {
    name: "TK Matcha",
    price: "49php",
    bgImage: "paper/paper6.jpeg",
    section: "blue",
    subSection: "Premium Milktea",
  },
  {
    name: "TK Dark Choco",
    price: "49php",
    bgImage: "paper/paper7.jpeg",
    section: "blue",
    subSection: "Premium Milktea",
  },
  {
    name: "TK Strawberry",
    price: "49php",
    bgImage: "paper/paper8.jpeg",
    section: "blue",
    subSection: "Premium Milktea",
  },
  {
    name: "TK Red Velvet",
    price: "49php",
    bgImage: "paper/paper9.jpeg",
    section: "blue",
    subSection: "Premium Milktea",
  },
  {
    name: "TK Buko Pandan",
    price: "49php",
    bgImage: "paper/paper10.jpeg",
    section: "blue",
    subSection: "Premium Milktea",
  },
  {
    name: "Iced Americano",
    price: "49php",
    bgImage: "rock/rock1.jpeg",
    section: "green",
    subSection: "Iced Coffee",
  },
  {
    name: "Iced Caramel Macchiato",
    price: "49php",
    bgImage: "rock/rock2.jpeg",
    section: "green",
    subSection: "Iced Coffee",
  },
  {
    name: "Iced Hazelnut",
    price: "49php",
    bgImage: "rock/rock3.jpeg",
    section: "green",
    subSection: "Iced Coffee",
  },
  {
    name: "Iced Latte",
    price: "49php",
    bgImage: "rock/rock4.jpeg",
    section: "green",
    subSection: "Iced Coffee",
  },
  {
    name: "Iced Spanish Latte",
    price: "49php",
    bgImage: "rock/rock5.jpeg",
    section: "green",
    subSection: "Iced Coffee",
  },
  {
    name: "Iced Matcha",
    price: "49php",
    bgImage: "rock/rock12.jpeg",
    section: "green",
    subSection: "Iced Coffee",
  },
  {
    name: "Americano",
    price: "49php",
    bgImage: "rock/rock0.jpeg",
    section: "green",
    subSection: "Hot Coffee",
  },
  {
    name: "Latte",
    price: "49php",
    bgImage: "rock/rock9.jpeg",
    section: "green",
    subSection: "Hot Coffee",
  },
  {
    name: "Cappucino",
    price: "49php",
    bgImage: "rock/rock8.jpeg",
    section: "green",
    subSection: "Hot Coffee",
  },
  {
    name: "Espresso",
    price: "49php",
    bgImage: "rock/rock7.jpeg",
    section: "green",
    subSection: "Hot Coffee",
  },
  {
    name: "Mocha",
    price: "49php",
    bgImage: "rock/rock09.jpeg",
    section: "green",
    subSection: "Hot Coffee",
  },
  {
    name: "Creamy Strawberry Frappe",
    price: "69php",
    bgImage: "scissors/s1.jpeg",
    section: "yellow",
    subSection: "Cream Based",
  },
  {
    name: "Matcha Frappe",
    price: "69php",
    bgImage: "scissors/s2.jpeg",
    section: "yellow",
    subSection: "Cream Based",
  },
  {
    name: "Dark Choco Frappe",
    price: "69php",
    bgImage: "scissors/s3.jpeg",
    section: "yellow",
    subSection: "Cream Based",
  },
  {
    name: "Choco Vanilla Frappe",
    price: "89php",
    bgImage: "scissors/s4.jpeg",
    section: "yellow",
    subSection: "Coffee Based",
  },
  {
    name: "Oreo Espresso Frappe",
    price: "89php",
    bgImage: "scissors/s5.jpeg",
    section: "yellow",
    subSection: "Coffee Based",
  },
  {
    name: "Creamy Biscoff Frappe",
    price: "89php",
    bgImage: "scissors/s6.jpeg",
    section: "yellow",
    subSection: "Coffee Based",
  },
  {
    name: "Nutty Coffee Frappe",
    price: "89php",
    bgImage: "scissors/s7.jpeg",
    section: "yellow",
    subSection: "Coffee Based",
  },
  {
    name: "Choco Caramel Frappe",
    price: "89php",
    bgImage: "scissors/s8.jpeg",
    section: "yellow",
    subSection: "Coffee Based",
  },
  {
    name: "rat 1",
    price: "$30",
    bgImage: "rat/1.jpeg",
    section: "violet",
    subSection: "Tea Based",
  },
  {
    name: "rat 2",
    price: "$35",
    bgImage: "rat/2.jpeg",
    section: "violet",
    subSection: "Tea Based",
  },
  {
    name: "rat 3",
    price: "$30",
    bgImage: "rat/3.jpeg",
    section: "violet",
    subSection: "Tea Based",
  },
  {
    name: "rat 4",
    price: "$35",
    bgImage: "rat/4.jpeg",
    section: "violet",
    subSection: "Soda Based",
  },
  {
    name: "rat 5",
    price: "$30",
    bgImage: "rat/5.jpeg",
    section: "violet",
    subSection: "Soda Based",
  },
  {
    name: "rat 6",
    price: "$35",
    bgImage: "rat/6.jpeg",
    section: "violet",
    subSection: "Soda Based",
  },
];