 const data = [
        {
          name: "Paper 1",
          price: "$10",
          bgImage: "paper/paper1.jpeg",
          section: "blue",
        },
        {
          name: "Paper 2",
          price: "$15",
          bgImage: "paper/paper2.jpeg",
          section: "blue",
        },
        {
          name: "Paper 3",
          price: "$10",
          bgImage: "paper/paper3.jpeg",
          section: "blue",
        },
        {
          name: "Paper 4",
          price: "$15",
          bgImage: "paper/paper4.jpeg",
          section: "blue",
        },
        {
          name: "Paper 5",
          price: "$10",
          bgImage: "paper/paper5.jpeg",
          section: "blue",
        },
        {
          name: "Paper 6",
          price: "$15",
          bgImage: "paper/paper6.jpeg",
          section: "blue",
        },
        {
          name: "Paper 7",
          price: "$10",
          bgImage: "paper/paper7.jpeg",
          section: "blue",
        },
        {
          name: "Paper 8",
          price: "$15",
          bgImage: "paper/paper8.jpeg",
          section: "blue",
        },
        {
          name: "Paper 9",
          price: "$10",
          bgImage: "paper/paper9.jpeg",
          section: "blue",
        },
        {
          name: "Rock 1",
          price: "$20",
          bgImage: "rock/rock1.jpeg",
          section: "green",
        },
        {
          name: "Rock 2",
          price: "$25",
          bgImage: "rock/rock2.jpeg",
          section: "green",
        },
        {
          name: "Rock 3",
          price: "$20",
          bgImage: "rock/rock3.jpeg",
          section: "green",
        },
        {
          name: "Rock 4",
          price: "$25",
          bgImage: "rock/rock4.jpeg",
          section: "green",
        },
        {
          name: "Rock 5",
          price: "$20",
          bgImage: "rock/rock5.jpeg",
          section: "green",
        },
        {
          name: "Rock 6",
          price: "$25",
          bgImage: "rock/rock6.jpeg",
          section: "green",
        },
        {
          name: "Rock 7",
          price: "$20",
          bgImage: "rock/rock7.jpeg",
          section: "green",
        },
        {
          name: "Rock 8",
          price: "$25",
          bgImage: "rock/rock8.jpeg",
          section: "green",
        },
        {
          name: "Rock 9",
          price: "$20",
          bgImage: "rock/rock9.jpeg",
          section: "green",
        },
        {
          name: "Scissor 1",
          price: "$30",
          bgImage: "scissors/s1.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 2",
          price: "$35",
          bgImage: "scissors/s2.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 3",
          price: "$30",
          bgImage: "scissors/s3.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 4",
          price: "$35",
          bgImage: "scissors/s4.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 5",
          price: "$30",
          bgImage: "scissors/s5.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 6",
          price: "$35",
          bgImage: "scissors/s6.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 7",
          price: "$30",
          bgImage: "scissors/s7.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 8",
          price: "$35",
          bgImage: "scissors/s8.jpeg",
          section: "yellow",
        },
        {
          name: "Scissor 9",
          price: "$30",
          bgImage: "scissors/s9.jpeg",
          section: "yellow",
        },
      ];